data <- read.table("household_power_consumption.txt", header=TRUE, sep=";")
data[,1] <- as.Date(data[,1], "%d/%m/%Y")
data <- data[data$Date == "2007-02-01" | data$Date == "2007-02-02", ]
data[,3] <- as.numeric(as.character(data[,3]))
data[,2] <- as.POSIXct(paste(data[,1], data[,2], sep=" "))
data[,4] <- as.numeric(as.character(data[,4]))
data[,5] <- as.numeric(as.character(data[,5]))
data[,7] <- as.numeric(as.character(data[,7]))
data[,8] <- as.numeric(as.character(data[,8]))
data[,9] <- as.numeric(as.character(data[,9]))
png(filename="plot4.png", width=480, height=480, units="px")
par(mfrow=c(2,2))
plot(data[,2], data[,3],xlab="", ylab="Global Active Power (kilowatts)" ,type="n")
lines(data[,2], data[,3], type="l")
plot(data[,2], data[,5], xlab="datetime", ylab="Voltage", type="n")
lines(data[,2], data[,5], type="l")
plot(data[,2], data[,7], xlab="", ylab="Energy Sub Metering" , type="n")
lines(data[,2], data[,7], col="black", type="l")
lines(data[,2], data[,8], col="red", type="l")
lines(data[,2], data[,9], col="blue", type="l")
legend("topright", pch="-", col=c("black", "red", "blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(data[,2], data[,4], xlab="datetime", ylab="Global_reactive_power", type="n")
lines(data[,2], data[,4], type="l")
dev.off()
